# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/hdl_projects/arty_z7_sdsoc/hw/vivado/arty_z7_sdsoc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_3/design_1_proc_sys_reset_0_3.xci
# IP: The module: 'design_1_proc_sys_reset_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/hdl_projects/arty_z7_sdsoc/hw/vivado/arty_z7_sdsoc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_3/design_1_proc_sys_reset_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/hdl_projects/arty_z7_sdsoc/hw/vivado/arty_z7_sdsoc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_3/design_1_proc_sys_reset_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/hdl_projects/arty_z7_sdsoc/hw/vivado/arty_z7_sdsoc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_3/design_1_proc_sys_reset_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/hdl_projects/arty_z7_sdsoc/hw/vivado/arty_z7_sdsoc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_3/design_1_proc_sys_reset_0_3.xci
# IP: The module: 'design_1_proc_sys_reset_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/hdl_projects/arty_z7_sdsoc/hw/vivado/arty_z7_sdsoc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_3/design_1_proc_sys_reset_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/hdl_projects/arty_z7_sdsoc/hw/vivado/arty_z7_sdsoc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_3/design_1_proc_sys_reset_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/hdl_projects/arty_z7_sdsoc/hw/vivado/arty_z7_sdsoc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_3/design_1_proc_sys_reset_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
