# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {BD 41-1348}  -new_severity {INFO} 
set_msg_config  -ruleid {2}  -id {BD 41-1343}  -new_severity {INFO} 
set_msg_config  -ruleid {3}  -id {BD 41-1306}  -new_severity {INFO} 
set_msg_config  -ruleid {4}  -id {IP_Flow 19-1687}  -new_severity {INFO} 
set_msg_config  -ruleid {5}  -id {filemgmt 20-1763}  -new_severity {INFO} 
set_msg_config  -ruleid {6}  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR} 
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.cache/wt [current_project]
set_property parent.project_path C:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/aptay/Downloads/hdl-hdl_2016_r2/library [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  C:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/imports/hdl/system_wrapper.v
  C:/Users/aptay/Downloads/hdl-hdl_2016_r2/projects/ad9467_fmc/common/ad9467_spi.v
  C:/Users/aptay/Downloads/hdl-hdl_2016_r2/library/xilinx/common/ad_iobuf.v
  C:/Users/aptay/Downloads/hdl-hdl_2016_r2/projects/ad9467_fmc/zed/system_top.v
}
add_files C:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_hdmi_clkgen_0/axi_clkgen_constr.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_hdmi_core_0/axi_hdmi_tx_constr.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/common/ad_axi_ip_constr.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_spdif_tx_core_0/axi_spdif_tx_constr.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_i2s_adi_0/axi_i2s_adi_constr.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_iic_fmc_0/system_axi_iic_fmc_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_iic_fmc_0/system_axi_iic_fmc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_ad9467_0/axi_ad9467_constr.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/common/ad_axi_ip_constr.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_axi_ad9467_dma_0/system_axi_ad9467_dma_0_constr.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files C:/hdl_projects/ad9467_fmc_zed/hw/vivado/ad9467_fmc_zed.srcs/sources_1/bd/system/system.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/aptay/Downloads/hdl-hdl_2016_r2/projects/common/xilinx/compression_system_constr.xdc
set_property used_in_implementation false [get_files C:/Users/aptay/Downloads/hdl-hdl_2016_r2/projects/common/xilinx/compression_system_constr.xdc]

read_xdc C:/Users/aptay/Downloads/hdl-hdl_2016_r2/projects/ad9467_fmc/zed/system_constr.xdc
set_property used_in_implementation false [get_files C:/Users/aptay/Downloads/hdl-hdl_2016_r2/projects/ad9467_fmc/zed/system_constr.xdc]

read_xdc C:/Users/aptay/Downloads/hdl-hdl_2016_r2/projects/common/zed/zed_system_constr.xdc
set_property used_in_implementation false [get_files C:/Users/aptay/Downloads/hdl-hdl_2016_r2/projects/common/zed/zed_system_constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_top -part xc7z020clg484-1


write_checkpoint -force -noxdef system_top.dcp

catch { report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb }
